version: '3.8'

services:
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: kamilekkamilekkamilek  
  #     MYSQL_DATABASE: logicpanel_db      
  #     MYSQL_USER: logicuser              
  #     MYSQL_PASSWORD: NPqw0fk6!pz7+     
  #   ports:
  #     - "3306:3306"                      
  #   volumes:
  #     - mysql-data:/var/lib/mysql        

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql                  
      PMA_PORT: 3306                    
      MYSQL_ROOT_PASSWORD: rootpassword 
    ports:
      - "80:80"                       

volumes:
  mysql-data:
